services:
  db:
    image: mariadb:latest
    container_name: vives_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Cambia esto si quieres
      MYSQL_DATABASE: vives_db
      MYSQL_USER: user_vives
      MYSQL_PASSWORD: password_vives
    ports:
      - "3306:3306"
    volumes:
      - ./docs/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: